///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesAvatarMan = 'assets/images/avatarMan.png';
  static const String imagesAvatarWoman = 'assets/images/avatarWoman.webp';
  static const String imagesFinal = 'assets/images/final.png';
  static const String imagesInitial = 'assets/images/initial.png';
  static const String imagesLogo = 'assets/images/logo.png';
  static const String imagesTracking = 'assets/images/tracking.png';
  static const String imagesUberExec = 'assets/images/uberExec.png';
  static const String soundsAlertSound = 'assets/sounds/alert_sound.mp3';

}
